name: safe_zone
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.3.0+1
  dartz: ^0.10.1
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  flex_color_scheme: ^8.1.1
  google_fonts: ^6.2.1
  toastification: ^2.3.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_hooks: ^0.21.2
  firebase_storage: ^12.4.7
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  flutter_datetime_picker_plus: ^2.2.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  timeago: ^3.7.1
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.15
  freezed: ^2.5.8
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/carousal/
