// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKrX_PmFqLiRUu1ATQEVdXEF3RtZYgeE',
    appId: '1:158012196368:web:f11dee65f071bdefa2ac95',
    messagingSenderId: '158012196368',
    projectId: 'fyp-safe-zone',
    authDomain: 'fyp-safe-zone.firebaseapp.com',
    storageBucket: 'fyp-safe-zone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHBFoxOZQB74GQzaI-_Pw5DDIj9IKP43M',
    appId: '1:158012196368:android:ee36cb93d18b803ba2ac95',
    messagingSenderId: '158012196368',
    projectId: 'fyp-safe-zone',
    storageBucket: 'fyp-safe-zone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALhhw_IlpVECwPGTqP0KkUfho1FoMQI1M',
    appId: '1:158012196368:ios:f64cae4a3f6c00d0a2ac95',
    messagingSenderId: '158012196368',
    projectId: 'fyp-safe-zone',
    storageBucket: 'fyp-safe-zone.firebasestorage.app',
    iosBundleId: 'com.miraclehousedev.safeZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALhhw_IlpVECwPGTqP0KkUfho1FoMQI1M',
    appId: '1:158012196368:ios:f64cae4a3f6c00d0a2ac95',
    messagingSenderId: '158012196368',
    projectId: 'fyp-safe-zone',
    storageBucket: 'fyp-safe-zone.firebasestorage.app',
    iosBundleId: 'com.miraclehousedev.safeZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzKrX_PmFqLiRUu1ATQEVdXEF3RtZYgeE',
    appId: '1:158012196368:web:d8b4edb2e7a1ec46a2ac95',
    messagingSenderId: '158012196368',
    projectId: 'fyp-safe-zone',
    authDomain: 'fyp-safe-zone.firebaseapp.com',
    storageBucket: 'fyp-safe-zone.firebasestorage.app',
  );

}